kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tiketi-local
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # Backend API
      - containerPort: 30000
        hostPort: 3001
        protocol: TCP
      # Frontend (optional)
      - containerPort: 30001
        hostPort: 3000
        protocol: TCP
      # Grafana Dashboard
      - containerPort: 30002
        hostPort: 3002
        protocol: TCP
      # PostgreSQL (for debugging)
      - containerPort: 30432
        hostPort: 5432
        protocol: TCP
  - role: worker
    labels:
      workload: application
  - role: worker
    labels:
      workload: data
