server:
  http_listen_port: 9080
# Promtail 자신도 상태 확인을 위한 포트가 필요합니다. (보통 잘 안 씁니다)

positions:
  filename: /tmp/positions.yaml
# [아주 중요] "책갈피" 기능입니다.
# 로그는 계속 쌓이는데, Promtail이 재부팅되면 처음부터 다시 읽으면 안 되겠죠?
# "나 여기까지 읽었어"라고 기록해두는 파일입니다. 중복 수집을 막아줍니다.

clients:
  - url: http://loki:3100/loki/api/v1/push
# 배달지 주소입니다.
# "http://loki:3100"에서 "loki"는 나중에 docker-compose에서 정의할 서비스 이름(Service Name)입니다.
# 같은 도커 네트워크 안에 있으니 이름으로 통신이 가능합니다.

scrape_configs: # 수집 규칙
  - job_name: docker
    # 도커 데몬에게 직접 물어보는 설정
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    # 가져온 정보 중 '컨테이너 이름'을 라벨로 예쁘게 만드는 설정
    relabel_configs:
      - target_label: job
        replacement: docker
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"
